Add default resolution var for teamviewer usage
papampi/nvOC_by_fullzero pull request #183
Opened 2018-08-21 00:23 UTC by Spiral11

By default connecting via teamviewer uses 800x600, this lets the user specify system resolution in 1bash which is then set if teamviewer is enabled in 3main.

2018-08-21 05:35 UTC, papampi commented
Great idea...
Does this affect system resolution or only teamviewer resolution?

2018-08-21 13:18 UTC, Spiral11 commented
System resolution

2018-08-21 20:31 UTC, Spiral11 commented
I'm not particularly fluent in using GitHub and just added an option to set SHUTDOWN_TEMP in 1bash which then makes the computer poweroff if whatever temperature set is exceeded. Also sends a telegram if either telegram_alerts or telegram_messages is enabled. I wanted this option since for closed setups like in a grow tent should the exhaust fan ever fail it can create an extreme hotbox quickly so I like the peace of mind in having pc shutdown should this ever happen.

Would have made a seperate pull request for this but didn't realize those changes would be auto-merged into this pull request.

2018-08-22 22:02 UTC, papampi reviewed
Good idea ...

2018-08-22 22:02 UTC, papampi commented on 6tempcontrol
> +          /usr/bin/curl -m 5 -s -X POST --output /dev/null https://api.telegram.org/bot$TELEGRAM_APIKEY/sendMessage -d "text=GPU$GPU exceeded $SHUTDOWN_TEMP c. System shutting down." -d chat_id=$TELE
Since most of telegram scripts shows warning just echo a warning and call telegram to run
```
echo "GPU$GPU exceeded $SHUTDOWN_TEMP c. System shutting down." | tee -a "$LOG_FILE"
if [[ $TELEGRAM_ALERTS == "YES" ]] || [[ $TELEGRAM_MESSAGES == "YES" ]]
then
  bash "${NVOC}/telegram" &
fi
```

2018-08-22 22:02 UTC, papampi commented on 6tempcontrol
> +    if [[ $CURRENT_TEMP -gt $SHUTDOWN_TEMP ]]
We need an option so users can chose if they want the HOT_SHUTDOWN or not
`if [[ $CURRENT_TEMP -gt $SHUTDOWN_TEMP ]] && [[ $HOT_SHUTDOWN == "YES" ]]`
Also in 1bash, before SHUTDOWN_TEMP

2018-08-23 02:22 UTC, Spiral11 commented
I personally use a modified version of the damNmad telegram and I'm not sure if that sends warnings from logs, I took a quick glance at the standard telegram file in nvoc repo and didn't see this functionality nor in the BaliMiner version either.

In the interest of keeping the telegram alert working in all of the telegram options would it make sense to keep the curl method instead? I merged the other hot_shutdown var change.

2018-08-23 12:44 UTC, papampi commented
All good
Please add revision number and a small info and we are good to go...

2018-08-23 14:10 UTC, Spiral11 commented
nvOC_1bash_ver="0038"
nvOC_1bash_least_compatible="0034"
nvOC_1bash_last_compatible="0035"

Would the compatible lines need to be changed? Not sure what happens if the variables don't exist in the 1bash.

2018-08-23 14:17 UTC, papampi commented
Hot shutdown will be ignored for sure, 
No idea what happens if teamviewer is yes and no resolution in 1bash, can you test?

2018-08-23 14:44 UTC, Spiral11 commented
Deleting $RESOLUTION from 1bash seems to just make the xrandr cmd fail and everything continues as normal. Resolution defaults to either 640x480 or 800x600 not sure which it is.

2018-08-23 14:49 UTC, papampi commented
So we can have this in 3main to keep it at default if setting was missing, or a bit higher?
```
if [[ $RESOLUTION == "" ]]
then
RESOLUTION="800x600"
fi

2018-08-23 14:52 UTC, papampi commented
Or if resolution exists set it
```
if [[ $RESOLUTION != "" ]]
then
xrandr ....

2018-08-23 15:03 UTC, Spiral11 commented
If $RESOLUTION does not exist then 'xrandr --fb ' runs which just returns a message asking for parameters so not sure if we need to bother checking it with another if statement. If we do then I think I prefer the 2nd option since there will already be a 'default' setting in the 1bash template of 1366x768 anyway which I chose since it's a 16:9 resolution and most people use widescreen monitors nowadays.

2018-08-23 15:10 UTC, papampi requested changes

2018-08-23 15:10 UTC, papampi commented on 3main
> +    echo "Setting Resolution to $RESOLUTION"
I think its best to add before echo ...
```
if [[ $RESOLUTION != "" ]]
then

2018-08-23 15:14 UTC, papampi approved these changes

2018-08-23 15:14 UTC, papampi commented
If you have nothing more to add we can merge it

2018-08-23 15:15 UTC, Spiral11 commented
Sounds good, merge away 👍

2018-08-23 15:16 UTC, merged

2018-08-23 15:20 UTC, papampi commented
@Spiral11 ,Thanks.

2018-08-27 11:18 UTC, LuKePicci commented
Mmm this would quite useful to me right now that I’m almost 1700 kilometers away from my rig… the temptation of a crazy remote upgrade is high..